blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/InnovativeDevSolutions/launcher/discussions
    about: Please ask questions and start discussions here
