name: CI

on:
  push:
    branches: [ "master", "develop" ]
    paths-ignore:
      - '.github/**'
      - '*.md'
      - '**/*.md'
  pull_request:
    branches: [ "master", "develop" ]
    paths-ignore:
      - '.github/**'
      - '*.md'
      - '**/*.md'

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  quality-check:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install frontend dependencies
        run: bun install

      - name: Check frontend build
        run: bun run build

      - name: Run frontend tests
        run: bun test || echo "No frontend tests found"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Check Rust formatting
        working-directory: ./src-tauri
        run: cargo fmt -- --check

      - name: Run Rust linter
        working-directory: ./src-tauri
        run: cargo clippy -- -D warnings

      - name: Run Rust tests
        working-directory: ./src-tauri
        run: cargo test
